config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get '/about', to: 'pages#about', as: :about_us
  get '/contact',to: 'pages#contact'
  # verb  path    to   controller#controller_action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
    # raise
    @team = %w(Iri Val Rich Annie Andreea)

    member = params[:member]

    if member.present?
      @team = @team.select { |name| name.start_with?(member) }
    end

  end

  def home
    @date = Date.today.strftime("%A, %b %d")
  end


end


# Params is a hash populated with data from 2 places
# - get request query - url
# - post request body

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="background-color: pink; padding: 16px;">
      <ul>
        <li><%= link_to 'About', about_us_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptate architecto quidem dolores quod! Eligendi nesciunt architecto, fugit? Pariatur unde in tempore nihil, voluptates harum officiis consequuntur atque consectetur! Quia, non.</p>

app/views/pages/contact.html.erb
<h1>Contact us</h1>


<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?" value="<%= params[:member] %>">
  <input type="submit">
</form>


<ul>
  <% @team.each do |name| %>
    <li><%= name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Our first baby app</h1>

<%= @date %>